name:                monkey-interpreter
version:             0.1.0.0
github:              "rudydiegas/monkey-interpreter"
license:             BSD-3-Clause
author:              "Rudy Sorensen"
maintainer:          "rudydsorensen@gmail.com"
copyright:           "2025 Rudy Sorensen"

description:
  An interpreter for the Monkey language. Mostly following along with the
  implementation detailed in Thorsten Ball's "Writing an Interpreter in Go"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:
  - src
  dependencies:
  - text

executables:
  monkey-interpreter-exe:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monkey-interpreter
    - text
    - bytestring

tests:
  monkey-interpreter-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monkey-interpreter
    - bytestring
    - hspec
    - text
    build-tools:
    - hspec-discover
