# TODO: is this okay for the snapshot config?
snapshot: lts-23.0
snapshot: nightly-2024-12-13
snapshot: ghc-9.8.4
snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/23/24.yaml

# TODO: figure out the packages configuration
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai

packages:
- .
